### ISSUE TITLE
npm warning when installing

### ISSUE THREAD

**Issue by YaacovTarko** [cmake-js/fastcall#19]
I installed fastcall and it seems to work, but I got the warning: 
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

Is this a known issue? Is it a cause for concern?

**Comment by unbornchikken** [comment]
Please ignore that warning for now. I don't want my module to depend on npm, that's why I stick to that outdated but working tiny module. I'm thinking on better solutions but it's on low priority because I don't want to fix things when they are working, you know.
