### ISSUE TITLE
Visual Studio is installed, but ERR! OMG There is no Visual C++ compiler installed 

### ISSUE THREAD

**Issue by grrrwaaa** [cmake-js/fastcall#26]
Hi there,

Tried running npm install --save fastcall in the node.js command line

Getting a build failure here with output: ERR! OMG There is no Visual C++ compiler installed. 

However this machine does have Visual Studio 2015 installed with C++ components. 

Tried running npm install --save fastcall in the VS2015 native tools command line; same result.
Running vcvarsall.bat beforehand doesn't help. 

npm install cmake-js worked fine.

Next tried opening a Git Bash shell:
git clone --recursive https://github.com/cmake-js/fastcall.git
cd fastcall
npm install

Same error.

Other than warnings about Nan:: calls being deprecated, I can't see anything amiss. 

node -v: v6.11.4
npm v: 3.10.10

Windows 10 64-bit

**Comment by grrrwaaa** [comment]
Looks like it may be a cmake-js problem, since it throws in https://github.com/cmake-js/cmake-js/blob/43fc6b44c568680633980e016dfec153ce650b52/lib/es6/toolset.js#L187

Looks the same as https://github.com/cmake-js/cmake-js/issues/78

**Comment by grrrwaaa** [comment]
Using Visual Studio Community 2015
Version 14.0.254.20.01 Update 3

**Comment by grrrwaaa** [comment]
Installing a fresh copy of VS 2017 Community did not help either.

**Comment by grrrwaaa** [comment]
Trying on an entirely different machine; newly installed Windows 10 Pro 64-bit, Node.js LTS 8.9.4 (x64), npm 5.6.0. Visual Studio Community 2015 Version 14.0.254.20.01 Update 3 is installed and can compile a simple C++ project.

npm install cmake-js succeeds.
npm install fastcall fails with the same error: OMG There is no Visual C++ compiler installed

**Comment by grrrwaaa** [comment]
Tried cloning the fastcall repo and running "npm install" -- same result. 

`ERR! OMG There is no Visual C++ compiler installed. Install Visual C++ Build Toolset or Visual Studio.                                               ERR! OMG There is no Visual C++ compiler installed. Install Visual C++ Build Toolset or Visual Studio.                                               npm ERR! code ELIFECYCLE                                                                                                                             npm ERR! errno 1                                                                                                                                     npm ERR! fastcall@0.2.4 install: `cmake-js compile`                                                                                                  npm ERR! Exit status 1                                                                                                                               npm ERR!                                                                                                                                             npm ERR! Failed at the fastcall@0.2.4 install script.                                                                                                npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                                                                                                        npm ERR! A complete log of this run can be found in:                                                                                                 npm ERR!     C:\Users\an\AppData\Roaming\npm-cache\_logs\2018-02-24T19_25_18_186Z-debug.log`

**Comment by grrrwaaa** [comment]
Wow. Updating Cmake to 3.11 fixed it.

**Comment by lal12** [comment]
I had the same error, turned out to be cmake-js/cmake-js#137 which was fixed. So fastcall should update its cmake-js dependency to the newest version.

**Comment by Seia-Soto** [comment]
Still no updates? I am experiencing same with Cmake 3.15 installed with visual studio 2015 update 3.
